# This package is not intended to be published.
name: vm
# version: do-not-upload
description: VM specific Dart code and helper scripts

dependencies:
  build_integration:
    git:
      url: https://github.com/alibaba-flutter/sdk.git
      ref: v1.17.0
      path: pkg/build_integration
  front_end: ^0.1.6
  kernel: ^0.3.6

dev_dependencies:
  args: ^1.4.4
